// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYRXU04F7yUdSmGNrJ-mTvIlSjA4MN2PA',
    appId: '1:197572962595:web:62bd54c8066407b13d8496',
    messagingSenderId: '197572962595',
    projectId: 'rayyan-cf0b7',
    authDomain: 'rayyan-cf0b7.firebaseapp.com',
    databaseURL: 'https://rayyan-cf0b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rayyan-cf0b7.firebasestorage.app',
    measurementId: 'G-2YFPCZBBBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCldrqdKr5jDhuWcoJBuQGoxnOdenNEKhE',
    appId: '1:197572962595:android:74dd9fcc94e479143d8496',
    messagingSenderId: '197572962595',
    projectId: 'rayyan-cf0b7',
    databaseURL: 'https://rayyan-cf0b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rayyan-cf0b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXLDeU_ii7-S8XNCmQGyHQxME_UAAsh8w',
    appId: '1:197572962595:ios:94c778deef48cf233d8496',
    messagingSenderId: '197572962595',
    projectId: 'rayyan-cf0b7',
    databaseURL: 'https://rayyan-cf0b7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rayyan-cf0b7.firebasestorage.app',
    iosBundleId: 'com.aquaconnect.aquaConnect',
  );
}
